version: "3.7"

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/file
    cap_add:
      - IPC_LOCK
    command: "server -dev -dev-root-token-id=root"
    restart: unless-stopped

volumes:
  vault-data:
    driver: local
