apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-vault
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "credentials-role"
    vault.hashicorp.com/agent-inject-secret-config.txt: "credentials/secret"
spec:
  serviceAccountName: credentials-sa
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command:
        - /bin/bash
        - -c
        - |
          while true; do
            if [[ -f /vault/secrets/config.txt ]]; then
              # Assuming username and password are in the config.txt file
              username=$(grep -oP '^username=\K.*' /vault/secrets/config.txt)
              password=$(grep -oP '^password=\K.*' /vault/secrets/config.txt)
              if [[ -n "$username" && -n "$password" ]]; then
                echo "Username: $username"
                echo "Password: $password"
              else
                echo "Username or password not found in config.txt!"
              fi
            else
              echo "Secrets not found!"
            fi
            sleep 60
          done
